@personagemId = 000000000000000000000000

PUT http://localhost:3000/personagens/{{personagemId}}
Content-Type: application/json

{
    "nome": "Beth Smith Editada",
    "imagem": "https://rickandmortyapi.com/api/character/avatar/4.jpeg"
}
